controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    payment:
        path: /app/example/{provider}
        controller: App\Controller\PaymentController::purchase
        methods: POST
